import { Product, ProductCategory, Plan, Dealer, Policy, Claim, Commission } from './types'

export const mockCategories: ProductCategory[] = [
  {
    id: 'cat-1',
    name: 'Gadget',
    code: 'GADGET',
    description: 'Smartphone, Tablet, Laptop, and handheld electronic devices',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Wearable Accessories',
    code: 'WEARABLE',
    description: 'Smartwatch, TWS Earbuds, Fitness Tracker, and smart glasses',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Electronics',
    code: 'ELECTRONICS',
    description: 'Mirrorless Camera, Gaming Console, Smart TV, and home audio',
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    category_id: 'cat-1',
    name: 'SuperClaim Smartphone Protect',
    description: 'Comprehensive coverage for flagship and mid-range smartphones',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    category_id: 'cat-1',
    name: 'SuperClaim Laptop Shield',
    description: 'All-inclusive physical and electrical protection for laptops',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    category_id: 'cat-2',
    name: 'SuperClaim Wearable Care',
    description: 'Drop and liquid damage cover for smartwatches & earbuds',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockPlans: Plan[] = [
  {
    id: 'plan-1',
    product_id: 'prod-1',
    name: 'Silver Protect',
    price: 350000,
    duration_months: 12,
    coverage_types: ['physical_damage', 'water_damage'],
    max_claims: 2,
    max_claim_value_pct: 80.0,
    cooldown_days: 30,
    commission_rate: 10.0,
    kyc_required: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plan-2',
    product_id: 'prod-1',
    name: 'Gold Total Guard',
    price: 650000,
    duration_months: 12,
    coverage_types: ['physical_damage', 'water_damage', 'loss', 'short_circuit'],
    max_claims: 3,
    max_claim_value_pct: 100.0,
    cooldown_days: 14,
    commission_rate: 12.5,
    kyc_required: true, // KYC verification enabled
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plan-3',
    product_id: 'prod-3',
    name: 'Wearable Basic Care',
    price: 180000,
    duration_months: 12,
    coverage_types: ['physical_damage', 'water_damage'],
    max_claims: 1,
    max_claim_value_pct: 80.0,
    cooldown_days: 30,
    commission_rate: 15.0,
    kyc_required: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockDealers: Dealer[] = [
  {
    id: 'dlr-1',
    profile_id: 'prof-dlr-1',
    business_name: 'iBox Grand Indonesia Store',
    business_address: 'Grand Indonesia Mall Lt. 3, Jakarta Pusat',
    contact_person: 'Budi Santoso',
    bank_name: 'BCA',
    bank_account_number: '8820192841',
    bank_account_holder: 'PT Erajaya Swasembada Tbk',
    commission_rate: 12.0,
    commission_schedule: 'MONTHLY',
    status: 'ACTIVE',
    created_at: '2025-01-15T08:00:00Z',
    updated_at: '2025-01-15T08:00:00Z',
  },
  {
    id: 'dlr-2',
    profile_id: 'prof-dlr-2',
    business_name: 'Digimap Senayan City',
    business_address: 'Senayan City Lt. 2, Jakarta Selatan',
    contact_person: 'Siti Rahma',
    bank_name: 'Mandiri',
    bank_account_number: '124009812738',
    bank_account_holder: 'PT Mitra Adiperkasa Tbk',
    commission_rate: 10.0,
    commission_schedule: 'BIWEEKLY',
    status: 'ACTIVE',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 'dlr-3',
    profile_id: 'prof-dlr-3',
    business_name: 'Samsung Experience Store PIM',
    business_address: 'Pondok Indah Mall 2 Lt. 2, Jakarta',
    contact_person: 'Agus Wijaya',
    bank_name: 'BCA',
    bank_account_number: '5270918231',
    bank_account_holder: 'PT Trikomsel Oke',
    commission_rate: 15.0,
    commission_schedule: 'WEEKLY',
    status: 'ACTIVE',
    created_at: '2025-02-10T14:30:00Z',
    updated_at: '2025-02-10T14:30:00Z',
  },
]

export const mockPolicies: Policy[] = [
  {
    id: 'pol-1',
    policy_number: 'SC-2025-008912',
    plan_id: 'plan-2',
    dealer_id: 'dlr-1',
    user_id: 'usr-1',
    customer_name: 'Reza Pratama',
    customer_email: 'reza.pratama@gmail.com',
    customer_phone: '081298765432',
    device_category: 'Gadget',
    device_brand: 'Apple',
    device_model: 'iPhone 15 Pro 256GB Natural Titanium',
    serial_number: 'F2LXYZ9876Q',
    purchase_date: '2025-01-20',
    purchase_price: 20999000,
    start_date: '2025-01-20T10:00:00Z',
    end_date: '2026-01-20T10:00:00Z',
    status: 'ACTIVE',
    payment_ref: 'XND-INV-99201',
    payment_channel: 'BCA Virtual Account',
    paid_at: '2025-01-20T10:05:00Z',
    certificate_url: '/certificates/SC-2025-008912.pdf',
    created_at: '2025-01-20T10:00:00Z',
    updated_at: '2025-01-20T10:05:00Z',
  },
  {
    id: 'pol-2',
    policy_number: 'SC-2025-009450',
    plan_id: 'plan-1',
    dealer_id: 'dlr-2',
    user_id: 'usr-2',
    customer_name: 'Dewi Lestari',
    customer_email: 'dewi.lestari@yahoo.com',
    customer_phone: '081388127391',
    device_category: 'Gadget',
    device_brand: 'Samsung',
    device_model: 'Galaxy S24 Ultra 512GB Titanium Black',
    serial_number: 'R5CW3018ZXP',
    purchase_date: '2025-02-14',
    purchase_price: 21999000,
    start_date: '2025-02-14T11:00:00Z',
    end_date: '2026-02-14T11:00:00Z',
    status: 'ACTIVE',
    payment_ref: 'XND-INV-99881',
    payment_channel: 'QRIS Gopay',
    paid_at: '2025-02-14T11:02:00Z',
    certificate_url: '/certificates/SC-2025-009450.pdf',
    created_at: '2025-02-14T11:00:00Z',
    updated_at: '2025-02-14T11:02:00Z',
  },
]

export const mockClaims: Claim[] = [
  {
    id: 'clm-1',
    claim_ref: 'CLM-2025-00109',
    policy_id: 'pol-1',
    user_id: 'usr-1',
    incident_type: 'physical_damage',
    incident_date: '2025-02-18',
    incident_location: 'Stasiun MRT Bundaran HI, Jakarta',
    description: 'Layar iPhone retak parah setelah terjatuh dari saku saat menaiki eskalator stasiun.',
    claimed_amount: 5400000,
    approved_amount: 5000000,
    deductible_amount: 250000, // 5% of 5.000.000
    net_payout: 4750000, // 5.000.000 - 250.000
    status: 'PAYOUT_PROCESSING',
    kyc_status: 'PASSED',
    reviewed_by: 'usr-admin-1',
    reviewed_at: '2025-02-20T14:00:00Z',
    created_at: '2025-02-18T16:30:00Z',
    updated_at: '2025-02-21T09:00:00Z',
  },
  {
    id: 'clm-2',
    claim_ref: 'CLM-2025-00110',
    policy_id: 'pol-2',
    user_id: 'usr-2',
    incident_type: 'water_damage',
    incident_date: '2025-02-22',
    incident_location: 'Pantai Indah Kapuk, Jakarta Utara',
    description: 'Tersiram air kopi saat di cafe dan speaker mati total serta port charger lembab.',
    claimed_amount: 3200000,
    approved_amount: null,
    deductible_amount: 0,
    net_payout: null,
    status: 'UNDER_REVIEW',
    kyc_status: 'NOT_REQUIRED',
    created_at: '2025-02-22T19:00:00Z',
    updated_at: '2025-02-23T10:00:00Z',
  },
]

export const mockCommissions: Commission[] = [
  {
    id: 'comm-1',
    dealer_id: 'dlr-1',
    policy_id: 'pol-1',
    amount: 78000, // 12% of 650.000
    rate: 12.0,
    status: 'PENDING',
    period_batch: 'FEBRUARY-2025-P2',
    created_at: '2025-01-20T10:05:00Z',
    updated_at: '2025-01-20T10:05:00Z',
  },
  {
    id: 'comm-2',
    dealer_id: 'dlr-2',
    policy_id: 'pol-2',
    amount: 35000, // 10% of 350.000
    rate: 10.0,
    status: 'DISBURSED',
    disbursement_date: '2025-02-20T15:00:00Z',
    period_batch: 'FEBRUARY-2025-P1',
    created_at: '2025-02-14T11:02:00Z',
    updated_at: '2025-02-20T15:00:00Z',
  },
]
